provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-adaptive-sampling:
    lang: r-geospatial
    handler: ./fn-adaptive-sampling
    image: disarm/fn-adaptive-sampling:0.3.0
    environment:
      exec_timeout: 60
      write_timeout: 70
      read_timeout: 70
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.zero: true
