provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-adaptive-sampling:
    lang: r-geospatial
    handler: ./fn-adaptive-sampling
    image: disarm/fn-adaptive-sampling:0.2.2
